### ISSUE TITLE
I would prefer hyphens in the repository name rather than underscores

### ISSUE THREAD

**Issue by nickloman** [LooseLab/ONT_ARTIC_Summaries#2]
I think the title is self-evident.

**Comment by mattloose** [comment]
Thank you for raising this issue.

Our team will consider and evaluate your opinions carefully.

**Comment by nickloman** [comment]
Re-opening.

**Comment by mattloose** [comment]
Thanks for trying to reopen this issue. That’s super helpful of you. 

Rest assured that your issue is important to us and we will get back to you at some point when we think it worth taking the time and effort to deal with.
